### ISSUE TITLE
pressing `control + n` when the editor is focused throws an error

### ISSUE THREAD

**Issue by schester44** [schester44/quik-notes#4]
pressing `control + n` when the Editor is focused throws an error

**Comment by hiimalexjgarcia** [comment]
From what I can tell, the hotkey Control+N in Firefox and Chrome is reserved for opening a new window and can't (easily) be overridden. Out of curiosity, I edited the hotkey string at https://github.com/schester44/quik-notes/blob/4c2fcf9aac206c4ffab7b6ef736939396f7763f3/src/components/EditorWindow/Editor.js#L22 to read "mod+m" instead of "ctrl+m" and found that I could create new notes as expected by pressing Control+M. Is it feasible to choose a new hotkey?

**Comment by schester44** [comment]
@hiimalexjgarcia Very true, I was using `ctrl+n` because i'm on OSX where command + n opens a new window. `mod+n` may be a better alternative. I will give it ago.
